-- Fase 14: grupos musculares / partes del cuerpo sugeridos automaticamente
-- por nombre y categoria (columna nueva "muscle_groups", jsonb array de
-- texto). Sirve para agrupar ejercicios o excluirlos ante una lesion. Son
-- SUGERENCIAS -- revisalas y corregilas en la planilla antes de darlas por
-- definitivas. Matchea por el nombre actual (antes de cualquier correccion).
--
-- Correr en el SQL Editor de Supabase.

alter table exercises add column if not exists muscle_groups jsonb not null default '[]';

update exercises set muscle_groups = '["Dedos"]'::jsonb where name = '1 min activo / 1 min descanso' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos"]'::jsonb where name = '1 min activo / 2 min descanso' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos"]'::jsonb where name = '10 min activo / 10 min descanso' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos"]'::jsonb where name = '5 min activo / 3 min descanso' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos"]'::jsonb where name = '50:50 - De fácil a moderado' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos"]'::jsonb where name = '50:50 - De moderado a fácil' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos"]'::jsonb where name = '8 min activo / 5 min descanso' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos"]'::jsonb where name = 'ARC Corto' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos"]'::jsonb where name = 'ARC Largo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos"]'::jsonb where name = 'ARC Medio' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos"]'::jsonb where name = 'Kilometraje de Boulder AC' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Acondicionamiento de Core en Piso 1' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Acondicionamiento de Core en Piso 2' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Activación a Dos Brazos - Levantamiento - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Activación a Un Brazo - ISO - 10 s' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Activación a Un Brazo - Levantamientos - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Activaciones' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Activaciones a Un Brazo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo","Hombro"]'::jsonb where name = 'Activaciones de Hombro - ISO - 10 s' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho"]'::jsonb where name = 'Aperturas de Pecho - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho"]'::jsonb where name = 'Aperturas Inclinado - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Hombro"]'::jsonb where name = 'Compresión - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Piernas","Cadera"]'::jsonb where name = 'Constructor de Tensión' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Core - 3' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Core - Barra Fuerza 1' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Core - Barra Fuerza 2' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Core - Barra Progresión 1' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Core - Barra Progresión 2' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Core 7' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Core 8' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Core 9' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Core en Piso 1' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Core en Piso 2' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Core Equipo de Buceo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Antebrazo"]'::jsonb where name = 'Curl de Antebrazo con Mancuernas' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Bíceps"]'::jsonb where name = 'Curl de Bíceps - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Cadera","Piernas"]'::jsonb where name = 'Curl de Isquiotibiales en TRX - Repeticiones Medias' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Antebrazo"]'::jsonb where name = 'Curl Inverso - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Bíceps"]'::jsonb where name = 'Curl Martillo - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Dominada a Un Brazo - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Dominada a Un Brazo - Fuerza Máxima' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Dominadas - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Dominadas - Test de Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Dominadas Supinas - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Hombro"]'::jsonb where name = 'Elevación Lateral - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Hombro"]'::jsonb where name = 'Encogimiento de Hombros Inclinado - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Enhebrar la Aguja - Repeticiones Medias' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Espalda al Vacio' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Tríceps"]'::jsonb where name = 'Extensión de Tríceps - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Tríceps"]'::jsonb where name = 'Extensión de Tríceps en Supino - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Face Pulls - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho","Tríceps","Hombro"]'::jsonb where name = 'Flexiones - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho","Tríceps","Hombro"]'::jsonb where name = 'Flexiones a Un Brazo - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho","Tríceps","Hombro"]'::jsonb where name = 'Flexiones de Potencia' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho","Tríceps","Hombro","Espalda"]'::jsonb where name = 'Flexiones Escapulares - Repeticiones Medias' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho","Tríceps","Hombro"]'::jsonb where name = 'Fondos de Tríceps - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho","Tríceps","Hombro"]'::jsonb where name = 'Fondos en Barra - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Generación de Potencia' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Hollow Body Hold 30 s' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Hombro"]'::jsonb where name = 'Hombros a Prueba de Balas' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Lock Offs - 10 s' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Lock Offs a Un Brazo - 10 s' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Lock Offs de Densidad' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Negativas - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Negativas - Fuerza Máxima' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Negativas a Un Brazo - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb where name = 'Negativas a Un Brazo - Fuerza Máxima' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Tríceps"]'::jsonb where name = 'Patada de Tríceps - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Piernas"]'::jsonb where name = 'Peso Muerto - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Core"]'::jsonb where name = 'Plancha Copenhague 30 s' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Piernas"]'::jsonb where name = 'Powerlifting' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Hombro"]'::jsonb where name = 'Press Arnold - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho"]'::jsonb where name = 'Press de Banca - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Hombro"]'::jsonb where name = 'Press de Hombro con Mancuernas - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho"]'::jsonb where name = 'Press de Pecho - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho"]'::jsonb where name = 'Press de Pecho Inclinado - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Hombro","Tríceps","Piernas"]'::jsonb where name = 'Press de Pesa Rusa Invertida - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho","Tríceps","Hombro"]'::jsonb where name = 'Pseudo Flexiones - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Cadera","Piernas"]'::jsonb where name = 'Puente de Glúteos - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Pullover de Dorsales - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Hombro","Tríceps","Piernas"]'::jsonb where name = 'Push Press con Barra - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Piernas"]'::jsonb where name = 'Rack Pull - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Remo Arquero - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Remo Bajo - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Remo Colgado - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Remo Inclinado - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Hombro"]'::jsonb where name = 'Retracción Escapular con Mancuerna - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Hombro"]'::jsonb where name = 'Rotaciones de Hombro con Banda - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Hombro"]'::jsonb where name = 'Rotaciones de Hombro en Prono - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Hombro"]'::jsonb where name = 'Rotaciones de Hombro Sentado - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Pecho","Core"]'::jsonb where name = 'Rutina de Calistenia de 10 Minutos para Escaladores' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Hombro"]'::jsonb where name = 'Secuencia TRX IYT en Prono - Repeticiones Medias' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda","Hombro"]'::jsonb where name = 'Secuencia TRX IYT en Supino - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Piernas"]'::jsonb where name = 'Sentadilla Goblet - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Piernas"]'::jsonb where name = 'Sentadilla Trasera - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Superserie de Potencia de Tracción' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Cadera","Piernas","Core"]'::jsonb where name = 'Swings con Pesa Rusa - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Tracciones Anchas - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Espalda"]'::jsonb where name = 'Tracciones de Potencia' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Piernas"]'::jsonb where name = 'Zancada Caminando con Mancuernas - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'F2 Open - Levantamiento - Fácil' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'F2 Open - Levantamiento - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'F2 Open - Levantamiento - Máximo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'F2 Open - Levantamiento - Peak' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'F3 Half Crimp - Levantamiento - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'F3 Half Crimp - Levantamiento - Máximo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Half Crimp 4 - Levantamiento - Base' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Half Crimp 4 - Levantamiento - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Half Crimp 4 - Levantamiento - Máximo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Half Crimp 4 - Levantamiento - Test Máximo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Half Crimp 4 - Repeticiones - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Levantamientos de Reclutamiento de Flexores de Dedos' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'M2 Open - Levantamiento - Fácil' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'M2 Open - Levantamiento - Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'M2 Open - Levantamiento - Máximo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'M2 Open - Levantamiento - Peak' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Cadera","Piernas"]'::jsonb where name = 'Aductores de Cadera' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Calentamiento y Vuelta a la Calma' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Hombro"]'::jsonb where name = 'Dislocaciones de Hombro - Estiramiento con Tempo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Elevación en Barra - Lateral' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Bíceps"]'::jsonb where name = 'Estiramiento de Bíceps - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Estiramiento de Cuádriceps - Sentado - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Cadera","Piernas"]'::jsonb where name = 'Estiramiento de Flexor de Cadera en Pared - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Estiramiento de Gemelo en Pared - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Cadera","Piernas"]'::jsonb where name = 'Estiramiento de Isquiotibiales - Sentado - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Muñeca"]'::jsonb where name = 'Estiramiento de Muñeca - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Pecho"]'::jsonb where name = 'Estiramiento de Pecho - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Estiramiento Revolver - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Estiramiento Sleeper - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Estiramientos de Dedos - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Pecho","Tríceps","Hombro"]'::jsonb where name = 'Fire Hydrant - Pierna Flexionada - Desarrollo de Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Antebrazo"]'::jsonb where name = 'Flexibilidad de Antebrazo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Flexibilidad de Tobillo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Cadera","Piernas"]'::jsonb where name = 'Glúteos e Isquiotibiales' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Good Morning Sentado - Estiramiento con Tempo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Mantenimiento de Flexibilidad' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Movilidad Matutina' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Pancake - De Pie - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Pancake - Pulsos' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Patadas Frontales - Dinámico' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Patadas Laterales - Dinámico' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Espalda","Piernas"]'::jsonb where name = 'Peso Muerto Rumano a Una Pierna - Estiramiento con Tempo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Postura de Caballo - ISO - Estático Activo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Postura de Paloma - Contrae y Relaja' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Espalda"]'::jsonb where name = 'Pullover de Dorsales con Mancuerna - Estiramiento con Tempo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Piernas"]'::jsonb where name = 'Pulsos de Split Frontal - Dinámico' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Pulsos y Patadas' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general"]'::jsonb where name = 'Rana Supina - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Hombro"]'::jsonb where name = 'Rotación Externa con Banda - Contrae y Relaja' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Piernas"]'::jsonb where name = 'Sentadillas Cosaco - Estiramiento con Tempo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Piernas"]'::jsonb where name = 'Sentadillas Split - Estiramiento con Tempo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Piernas"]'::jsonb where name = 'Split Frontal - Nivel 1' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Piernas"]'::jsonb where name = 'Split Lateral - Nivel 1' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Piernas"]'::jsonb where name = 'Split Lateral ISO - Estático Activo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Piernas"]'::jsonb where name = 'Test de Split Lateral - Sin Apoyo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Movilidad general","Piernas"]'::jsonb where name = 'Zancada Larga ISO - Estático Pasivo' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = '30 Movimientos Fraccionados' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = '4x4' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = '5 Series Más Difíciles' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = '6 en 6' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'A Vista' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Boulders Enlazados' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Boulders Extendidos' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Dobles de Boulder' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Dobles de Ruta' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Kilometraje de Boulder - Intervalos Forzados' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Pirámide de Rutas' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Proyectando Rutas' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Proyecto de Capacidad Anaeróbica' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Test de Repeticiones al 60%' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Antebrazo"]'::jsonb where name = 'Triples de Boulder' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Campus - 3 Movimientos' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Circuitos de Boulder' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Eficiencia en Board' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Eliminados' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Encadenando a Vista (Flash)' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Encadenando Boulder' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Encadenando en Board' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Enfoque de Boulder' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Esfuerzos Máximos de Boulder' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Esfuerzos Máximos de Boulder Sin Pies' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Esfuerzos Máximos en Board' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Esfuerzos Máximos en Board - Extendido' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Intervalos de Fuerza' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Juego de Boulder' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Kilometraje de Boulder' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Pausas en Board' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Pirámide de Boulder' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Referencias de MoonBoard' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Sesión de Board' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Sesión de Competencia - Final' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Sesión de Competencia - Semifinal' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Tensión - Manos Fijas' and muscle_groups = '[]'::jsonb;
update exercises set muscle_groups = '["Dedos","Hombro"]'::jsonb where name = 'Volumen de Board' and muscle_groups = '[]'::jsonb;
