-- Fase 15: correcciones de nombre/descripcion y grupos musculares finales,
-- cargadas por el usuario en Catalogo_ejercicios_Apex_v2.xlsx. Matchea por
-- "code" (estable), no por nombre, asi que no importa que el nombre cambie.
-- CD0041 y CD0064 quedaron con el mismo nombre corregido ("Push up") en la
-- planilla; por acuerdo explicito quedan: CD0041 = "Push up" (flexiones de
-- piso), CD0064 = "Press de pecho con mancuernas" (antes "Press de Pecho -
-- Fuerza"). Grupos musculares normalizados (mayusculas/plural) y "escalada"
-- mapeado a "Escalada general" (grupo nuevo agregado a la taxonomia).
--
-- Correr en el SQL Editor de Supabase.

update exercises set name = '1 on / 1 off', muscle_groups = '["Dedos","Escalada general"]'::jsonb, description = 'Intervalos de intensidad media estructurados con proporción trabajo-descanso 1:1. Escala durante 1 minuto, descansa 1 minuto, y repite durante varias series. Objetivo: Estresar tu sistema de capacidad aeróbica con intervalos que se vuelven progresivamente más difíciles de recuperar hacia el final del entrenamiento. Descanso: 60 s entre series' where code = 'AB0001';
update exercises set name = '1 on / 2 off', muscle_groups = '["Dedos","Escalada general"]'::jsonb, description = 'Intervalos de intensidad media estructurados con proporción trabajo-descanso 1:2. Escala durante 1 minuto, descansa 2 minutos, y repite durante varias series. Objetivo: Estresar tu sistema de capacidad aeróbica con intervalos que permiten mayor recuperación, construyendo una base sólida de resistencia. Descanso: 2 min entre series' where code = 'AB0002';
update exercises set name = '10 on / 10 off', muscle_groups = '["Dedos","Escalada general"]'::jsonb, description = 'Escala de forma continua durante 10 minutos a intensidad muy baja, seguido de descanso, repetido durante varias series en rutas o circuitos. Objetivo: Promover la recuperación y el flujo sanguíneo mediante volumen de escalada de baja intensidad, reconstruyendo la base de resistencia sin agregar estrés significativo de entrenamiento. Descanso: 10 min entre series' where code = 'AB0003';
update exercises set name = '5 on / 3 off', muscle_groups = '["Dedos","Escalada general"]'::jsonb, description = 'Escala de forma continua durante 5 minutos a intensidad muy baja, seguido de descanso, repetido durante varias series en rutas o circuitos. Objetivo: Promover la recuperación mediante intervalos de escalada suave, aumentando el flujo sanguíneo para ayudar a la reparación de tejidos mientras se construye la base de resistencia. Descanso: 3 min entre series' where code = 'AB0004';
update exercises set name = '15+15 - facil a moderado', muscle_groups = '["Dedos","Escalada general"]'::jsonb, description = 'Alterna entre 15 movimientos fáciles y 15 movimientos moderados en cada repetición, practicando la habilidad de cambiar de intensidad a mitad de la escalada. Objetivo: Desarrollar la capacidad aeróbica mientras se aprende a adaptar el ritmo y el estilo de escalada entre secciones de distinta intensidad. Descanso: 10 min entre series' where code = 'AB0005';
update exercises set name = '15+15 - moderado a facil', muscle_groups = '["Dedos","Escalada general"]'::jsonb, description = 'Comienza cada repetición en una ruta moderada durante 15 movimientos, luego cambia a escalada más fácil durante los 15 movimientos restantes. Objetivo: Desarrollar la capacidad aeróbica mientras se aprende a manejar el bombeo y a transicionar entre intensidades de escalada. Descanso: 10 min entre series' where code = 'AB0006';
update exercises set name = '8 on / 5 off', muscle_groups = '["Dedos","Escalada general"]'::jsonb, description = 'Escala de forma continua durante 8 minutos a intensidad muy baja, seguido de descanso, repetido durante varias series en rutas o circuitos. Objetivo: Apoyar la recuperación y la base de resistencia mediante intervalos de escalada de baja intensidad y duración moderada, aumentando el flujo sanguíneo sin sobrecargar el sistema. Descanso: 5 min entre series' where code = 'AB0007';
update exercises set name = 'ARC bajo', muscle_groups = '["Dedos","Escalada general"]'::jsonb, description = 'Escala de forma continua durante 10 minutos a intensidad muy baja, manteniendo un movimiento fácil en rutas o circuitos sin acercarte al fallo. Objetivo: Promover la recuperación activa y construir una base aeróbica mediante un periodo sostenido de escalada fácil, apoyando el desarrollo de resistencia a largo plazo.' where code = 'AB0008';
update exercises set name = 'ARC largo', muscle_groups = '["Dedos","Escalada general"]'::jsonb, description = 'Escala de forma continua durante 30 minutos a intensidad muy baja, manteniendo un movimiento fácil en rutas o circuitos sin acercarte al fallo. Objetivo: Promover la recuperación activa y construir una base aeróbica mediante un bloque extendido de escalada fácil, apoyando el desarrollo de resistencia a largo plazo.' where code = 'AB0009';
update exercises set name = 'ARC medio', muscle_groups = '["Dedos","Escalada general"]'::jsonb, description = 'Escala de forma continua durante 20 minutos a intensidad muy baja, manteniendo un movimiento fácil en rutas o circuitos sin acercarte al fallo. Objetivo: Apoyar la recuperación activa y la construcción de la base aeróbica mediante un bloque de duración media de escalada fácil.' where code = 'AB0010';
update exercises set name = 'Boulder Volumen', muscle_groups = '["Dedos","Escalada general"]'::jsonb, description = 'Escala 10-20 boulders muy fáciles a baja intensidad, priorizando el ritmo y el movimiento fluido en todo momento. Objetivo: Desarrollar la capacidad aeróbica y la capilarización del antebrazo mediante boulder de alto volumen y muy baja intensidad.' where code = 'AB0011';
update exercises set name = 'Acondicionamiento de Core en Piso 1:
- Sit up
- Plancha lateral
- Plancha
- Piernas arriba
- Sit up', muscle_groups = '["Core"]'::jsonb, description = 'Acondicionamiento de Core en Piso 1: un circuito de 5 ejercicios que cubre core anterior, core lateral y core inferior, completado en 2 rondas con descanso mínimo entre ejercicios. Objetivo: Desarrollar el acondicionamiento del core y la resistencia muscular, mejorando tu capacidad de mantener la tensión corporal durante entrenamientos de escalada más largos. Descanso: 10 s entre series' where code = 'CD0001';
update exercises set name = 'Acondicionamiento de Core en Piso 2:
- Sit up
- Plancha lateral
- Plancha
- Piernas arriba
- Sit up', muscle_groups = '["Core"]'::jsonb, description = 'Acondicionamiento de Core en Piso 2: un circuito de 5 ejercicios que cubre core anterior, core lateral y core inferior, completado en 2 rondas con descanso mínimo entre ejercicios. Objetivo: Desarrollar el acondicionamiento del core y la resistencia muscular, mejorando tu capacidad de mantener la tensión corporal durante entrenamientos de escalada más largos. Descanso: 10 s entre series' where code = 'CD0002';
update exercises set name = 'Bloqueo 90', muscle_groups = '["Espalda","Bíceps","Antebrazo","Hombro"]'::jsonb, description = 'Este entrenamiento se centra en el bloqueo a 90° con dos brazos (levantamiento) dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en estabilizadores escapulares y dorsales, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0003';
update exercises set name = 'Contracción escapular a un brazo', muscle_groups = '["Espalda","Bíceps","Antebrazo","Hombro"]'::jsonb, description = 'Múltiples series de constracciones isométricas a un brazo de 10 s. Objetivo: Construir fuerza isométrica máxima de tracción en estabilizadores escapulares y dorsales, transfiriendose directamente a la capacidad de lock off en la pared. Descanso: 3 min entre series' where code = 'CD0004';
update exercises set name = 'Bloqueo 90 a un brazo', muscle_groups = '["Espalda","Bíceps","Antebrazo","Hombro"]'::jsonb, description = 'Completaras bloqueos a 90° con un brazo (levantamientos) dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en estabilizadores escapulares y dorsales, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0005';
update exercises set name = 'Activación escapular:: 
- Constracción escapular
- Bloqueos 90', muscle_groups = '["Espalda","Bíceps","Antebrazo","Hombro"]'::jsonb, description = 'Activaciones: un entrenamiento de tracción con varios ejercicios y múltiples series de cada uno. Objetivo: Desarrollar fuerza de tracción equilibrada en múltiples patrones de movimiento, construyendo la fuerza del tren superior esencial para la escalada. Descanso: 2 min entre series' where code = 'CD0006';
update exercises set name = 'Activación escapular a un brazo: 
- Constracción escapular
- Bloqueos 90', muscle_groups = '["Espalda","Bíceps","Antebrazo","Hombro"]'::jsonb, description = 'Activaciones: un entrenamiento de tracción con varios ejercicios y múltiples series de cada uno. Objetivo: Desarrollar fuerza de tracción equilibrada en múltiples patrones de movimiento, construyendo la fuerza del tren superior esencial para la escalada. Descanso: 2 min entre series' where code = 'CD0007';
update exercises set name = 'Constracción escapular', muscle_groups = '["Espalda","Bíceps","Antebrazo","Hombro"]'::jsonb, description = 'Múltiples series de constracciones isométricas de 20 s. Objetivo: Construir fuerza isométrica máxima de tracción en estabilizadores escapulares y dorsales, transfiriendose directamente a la capacidad de lock off en la pared. Descanso: 3 min entre series' where code = 'CD0008';
update exercises set name = 'Apertura de pecho', muscle_groups = '["Pecho","Hombro"]'::jsonb, description = 'Este entrenamiento se centra en aperturas de pecho dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en pecho y deltoides anteriores, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0009';
update exercises set name = 'Apertura de pecho - inclinado', muscle_groups = '["Pecho","Hombro"]'::jsonb, description = 'Este entrenamiento se centra en aperturas inclinado dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en deltoides posteriores y espalda alta, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0010';
update exercises set name = 'Fuerza compresión:
- Press banca
- Press pecho inclinado con mancuernas
- Bloqueos 90', muscle_groups = '["Pecho","Hombro"]'::jsonb, description = 'Este entrenamiento se centra en la compresión dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje equilibrada, manteniendo el equilibrio muscular alrededor de los hombros y reduciendo el riesgo de lesión por la naturaleza dominante de tracción de la escalada. Descanso: 3 min entre series' where code = 'CD0011';
update exercises set name = 'Tension corporal: 
- Rack pull
- Overhead Squat
- Remo con mancuernas', muscle_groups = '["Piernas","Cadera","Espalda"]'::jsonb, description = 'Constructor de Tensión: un entrenamiento de tren inferior con varios ejercicios y múltiples series de cada uno. Objetivo: Construir fuerza y potencia del tren inferior de forma completa, apoyando un trabajo de pies fuerte, movimiento dinámico y prevención de lesiones para la escalada. Descanso: 3 min entre series' where code = 'CD0012';
update exercises set name = 'Core 3:
- Plancha (pierna arriba)
- Push up
- Bote (pose V)
- Sit up
- Plancha lateral', muscle_groups = '["Core"]'::jsonb, description = 'Un circuito de 5 ejercicios que cubre core anterior, core lateral y trabajo de empuje, completado en 2 rondas con descanso mínimo entre ejercicios. Objetivo: Construir fuerza y estabilidad de core equilibrada mediante patrones de movimiento variados, apoyando directamente la tensión corporal y el control en la escalada. Descanso: 10 s entre series' where code = 'CD0013';
update exercises set name = 'Core Barra Fuerza 1:
- Pies a la barra (medio)
- L-sit
- Pies a la barra (lado a lado)
- Front lever (piernas 90)', muscle_groups = '["Core","Hombro"]'::jsonb, description = 'Core - Barra Fuerza 1: un entrenamiento de 4 ejercicios que combina distintos movimientos de core con varias series de cada uno. Objetivo: Construir fuerza de core equilibrada mediante ejercicios variados, desarrollando la estabilidad y la tensión corporal que sustenta todo movimiento de escalada. Descanso: 10 s entre series' where code = 'CD0014';
update exercises set name = 'Core Barra Fuerza 2:
- Pies a la barra (medio)
- L-sit
- Pies a la barra (lado a lado)
- Front lever (piernas 90)', muscle_groups = '["Core","Hombro"]'::jsonb, description = 'Core - Barra Fuerza 2: un entrenamiento de 4 ejercicios que combina distintos movimientos de core con varias series de cada uno. Objetivo: Construir fuerza de core equilibrada mediante ejercicios variados, desarrollando la estabilidad y la tensión corporal que sustenta todo movimiento de escalada. Descanso: 10 s entre series' where code = 'CD0015';
update exercises set name = 'Core Barra 1:
- Front lever (piernas pecho)
- Pies a la barra (lado a lado)
- L-sit
- Pies a la barra (medio)', muscle_groups = '["Core","Hombro"]'::jsonb, description = 'Core - Barra Progresión 1: un entrenamiento de 4 ejercicios que combina distintos movimientos de core con varias series de cada uno. Objetivo: Construir fuerza de core equilibrada mediante ejercicios variados, desarrollando la estabilidad y la tensión corporal que sustenta todo movimiento de escalada. Descanso: 10 s entre series' where code = 'CD0016';
update exercises set name = 'Core Barra 2:
- Front lever (piernas pecho)
- Pies a la barra (lado a lado)
- L-sit
- Pies a la barra (medio)', muscle_groups = '["Core","Hombro"]'::jsonb, description = 'Core - Barra Progresión 2: un entrenamiento de 4 ejercicios que combina distintos movimientos de core con varias series de cada uno. Objetivo: Construir fuerza de core equilibrada mediante ejercicios variados, desarrollando la estabilidad y la tensión corporal que sustenta todo movimiento de escalada. Descanso: 10 s entre series' where code = 'CD0017';
update exercises set name = 'Core 7:
- Pies a la barra
- Sit up con peso
- Piernas arriba
- Twist sit up
- Lumbares', muscle_groups = '["Core","Hombro"]'::jsonb, description = 'Core 7: un circuito de 5 ejercicios que cubre core anterior, core inferior y trabajo de core posterior, completado en 3 rondas con descanso mínimo entre ejercicios. Objetivo: Construir fuerza y estabilidad de core equilibrada mediante patrones de movimiento variados, apoyando directamente la tensión corporal y el control en la escalada. Descanso: 10 s entre series' where code = 'CD0018';
update exercises set name = 'Core 8:
- Pies a la barra
- Sit up con peso
- Piernas arriba
- Twist sit up
- Lumbares', muscle_groups = '["Core","Hombro"]'::jsonb, description = 'Core 8: un circuito de 5 ejercicios que cubre core anterior, core inferior y trabajo de core posterior, completado en 3 rondas con descanso mínimo entre ejercicios. Objetivo: Construir fuerza y estabilidad de core equilibrada mediante patrones de movimiento variados, apoyando directamente la tensión corporal y el control en la escalada. Descanso: 10 s entre series' where code = 'CD0019';
update exercises set name = 'Core 9:
- Sit up con peso
- V up
- Hollow body
- Plancha lateral (arriba - abajo)
- Plancha lateral
- Lumbares
- Push up
- Plancha', muscle_groups = '["Core"]'::jsonb, description = 'Un circuito de 9 ejercicios que cubre core anterior, core lateral y trabajo de core posterior, completado en 3 rondas con descanso mínimo entre ejercicios. Objetivo: Prefatigar el core con movimientos dinámicos antes de las sujeciones isométricas, construyendo resistencia muscular profunda y tensión corporal para una escalada sostenida. Descanso: 10 s entre series' where code = 'CD0020';
update exercises set name = 'Core Piso 1:
- V sits
- Hollow body
- Sit-up con peso
- Plancha lateral con peso
- Kettlebell twist', muscle_groups = '["Core"]'::jsonb, description = 'Core en Piso 1: un circuito de 5 ejercicios que cubre core anterior, core lateral y trabajo de core rotacional, completado en 2 rondas con descanso mínimo entre ejercicios. Objetivo: Construir fuerza y estabilidad de core equilibrada mediante patrones de movimiento variados, apoyando directamente la tensión corporal y el control en la escalada. Descanso: 10 s entre series' where code = 'CD0021';
update exercises set name = 'Core Piso 2::
- V sits
- Hollow body
- Sit-up con peso
- Plancha lateral con peso
- Kettlebell twist', muscle_groups = '["Core"]'::jsonb, description = 'Core en Piso 2: un circuito de 5 ejercicios que cubre core anterior, core lateral y trabajo de core rotacional, completado en 2 rondas con descanso mínimo entre ejercicios. Objetivo: Construir fuerza y estabilidad de core equilibrada mediante patrones de movimiento variados, apoyando directamente la tensión corporal y el control en la escalada. Descanso: 10 s entre series' where code = 'CD0022';
update exercises set name = 'Core:
- Plancha
- V up
- Lumbares
- Piernas arriba
- Sit up
- Twist sit up', muscle_groups = '["Core"]'::jsonb, description = 'Un circuito de 6 ejercicios que cubre core anterior, core inferior y trabajo de core posterior, completado en 10 rondas con descanso mínimo entre ejercicios. Objetivo: Construir fuerza y estabilidad de core equilibrada mediante patrones de movimiento variados, apoyando directamente la tensión corporal y el control en la escalada.' where code = 'CD0023';
update exercises set name = 'Curl antebrazo con mancuerna:
- Flexor muñeca (plama arriba)
- Flexor muñeca (palma abajo)', muscle_groups = '["Antebrazo","Muñeca"]'::jsonb, description = 'Completa curls de flexores y extensores de muñeca con mancuernas en varias series. Objetivo: Construir fuerza equilibrada de flexores y extensores de muñeca para mejorar la estabilidad del agarre y reducir el riesgo de lesión. Descanso: 60 s entre series' where code = 'CD0024';
update exercises set name = 'Curl de biceps', muscle_groups = '["Bíceps"]'::jsonb, description = 'Este entrenamiento se centra en el curl de bíceps dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en bíceps y antebrazos, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0025';
update exercises set name = 'Curl de isquiotibiales en TRX', muscle_groups = '["Cadera","Piernas"]'::jsonb, description = 'Realiza el curl de isquiotibiales en TRX dentro de un estímulo de repeticiones moderadas. Objetivo: Desarrollar fuerza del tren inferior en isquiotibiales y glúteos, mejorando tu capacidad de generar fuerza a través de pies y piernas mientras escalas. Descanso: 3 min entre series' where code = 'CD0026';
update exercises set name = 'Curl de bicep inverso', muscle_groups = '["Antebrazo"]'::jsonb, description = 'Completaras el curl inverso dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en braquiorradial y extensores del antebrazo, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0027';
update exercises set name = 'Curl de bicep martillo', muscle_groups = '["Bíceps"]'::jsonb, description = 'Completaras el curl martillo dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en braquiorradial, bíceps y antebrazos, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0028';
update exercises set name = 'Dominada a Un Brazo', muscle_groups = '["Espalda"]'::jsonb, description = 'Completaras la dominada a un brazo dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en dorsales, bíceps, antebrazos y core, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0029';
update exercises set name = 'Dominada a Un Brazo - Explosivas', muscle_groups = '["Espalda"]'::jsonb, description = 'Realiza la dominada a un brazo dentro de un estímulo de fuerza máxima. Objetivo: Reclutar la fuerza de tracción máxima en dorsales, bíceps, antebrazos y core, construyendo la fuerza de alto nivel necesaria para movimientos potentes en terreno vertical pronunciado. Descanso: 3 min entre series' where code = 'CD0030';
update exercises set name = 'Dominadas', muscle_groups = '["Espalda"]'::jsonb, description = 'Completaras las dominadas dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en dorsales, bíceps y antebrazos, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0031';
update exercises set name = 'Dominadas - Test de Fuerza', muscle_groups = '["Espalda"]'::jsonb, description = 'En este entrenamiento completaras el máximo de dominadas como prueba de tu fuerza actual. Objetivo: Reclutar la fuerza de tracción máxima en dorsales, bíceps y antebrazos, construyendo la fuerza de alto nivel necesaria para movimientos potentes en terreno vertical pronunciado. Descanso: 3 min entre series' where code = 'CD0032';
update exercises set name = 'Dominadas Supinas', muscle_groups = '["Espalda"]'::jsonb, description = 'Este entrenamiento se centra en dominadas supinas dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en dorsales, bíceps y antebrazos, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0033';
update exercises set name = 'Jalón pecho (brazos estirados)', muscle_groups = '["Hombro"]'::jsonb, description = 'Completa la elevación lateral dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en deltoides laterales, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0034';
update exercises set name = 'Encogimiento de Hombros Inclinado', muscle_groups = '["Espalda","Hombro"]'::jsonb, description = 'Completaras el encogimiento de hombros inclinado dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en trapecio superior y estabilizadores escapulares, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0035';
update exercises set name = 'Enhebrar la Aguja', muscle_groups = '["Core"]'::jsonb, description = 'Realiza enhebrar la aguja dentro de un estímulo de repeticiones moderadas. Objetivo: Desarrollar fuerza de empuje en columna torácica y hombros, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0036';
update exercises set name = 'Rutina de espalda:
- Remo con barra
- Pull up ancho
- Vuelos con mancuerna', muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb, description = 'Un entrenamiento de tracción con varios ejercicios y múltiples series de cada uno. Objetivo: Desarrollar fuerza de tracción equilibrada en múltiples patrones de movimiento, construyendo la fuerza del tren superior esencial para la escalada. Descanso: 3 min entre series' where code = 'CD0037';
update exercises set name = 'Extensión de Tríceps', muscle_groups = '["Tríceps"]'::jsonb, description = 'Completaras la extensión de tríceps dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en tríceps, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0038';
update exercises set name = 'Extensión de Tríceps en Supino', muscle_groups = '["Tríceps"]'::jsonb, description = 'Realiza extensión de tríceps en supino dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en tríceps, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0039';
update exercises set name = 'Face Pulls', muscle_groups = '["Espalda"]'::jsonb, description = 'Realiza face pulls dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en deltoides posteriores, romboides y rotadores externos, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0040';
update exercises set name = 'Push up', muscle_groups = '["Pecho","Tríceps","Hombro"]'::jsonb, description = 'Completa flexiones dentro de un estímulo de fuerza. Objetivo: Empujar hacia arriba a través del pecho, tríceps y hombros anteriores desarrolla la fuerza detras de los mantle y los movimientos de compresión, manteniendo el equilibrio muscular. Descanso: 3 min entre series' where code = 'CD0041';
update exercises set name = 'Push up a Un Brazo', muscle_groups = '["Pecho","Tríceps","Hombro"]'::jsonb, description = 'Completaras las flexiones a un brazo dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en pecho, tríceps y hombros, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0042';
update exercises set name = 'Push up explosivas', muscle_groups = '["Pecho","Tríceps","Hombro"]'::jsonb, description = 'Este entrenamiento se centra en flexiones de potencia. Objetivo: Construir fuerza de empuje máxima en pecho, tríceps y hombros, manteniendo el equilibrio muscular alrededor de la articulación del hombro y reduciendo el riesgo de lesión. Descanso: 5 min entre series' where code = 'CD0043';
update exercises set name = 'Flexiones Escapulares', muscle_groups = '["Pecho","Tríceps","Hombro","Espalda"]'::jsonb, description = 'Completaras las flexiones escapulares dentro de un estímulo de repeticiones moderadas. Objetivo: Desarrollar fuerza de empuje en pecho, tríceps y hombros, mejorando tu capacidad de empujar y estabilizar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0044';
update exercises set name = 'Fondos de Tríceps', muscle_groups = '["Pecho","Tríceps","Hombro"]'::jsonb, description = 'Completa fondos de tríceps dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en pecho, tríceps y deltoides anteriores, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0045';
update exercises set name = 'Fondos en Barra', muscle_groups = '["Pecho","Tríceps","Hombro"]'::jsonb, description = 'Completa fondos en barra dentro de un estímulo de fuerza. Objetivo: Este rango perfecciona una fuerza de empuje confiable. Con los tríceps, el pecho inferior y los deltoides anteriores impulsando el movimiento, desarrollas la musculatura necesaria para rematar y empujar sobre regletas inclinadas. Descanso: 3 min entre series' where code = 'CD0046';
update exercises set name = 'Generación de Potencia:
- Dominadas explosivas
- Push up explosivas
- Jumpin jacks', muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb, description = 'Generación de Potencia: un entrenamiento de tracción con varios ejercicios y múltiples series de cada uno. Objetivo: Desarrollar fuerza de tracción equilibrada en múltiples patrones de movimiento, construyendo la fuerza del tren superior esencial para la escalada. Descanso: 3 min entre series' where code = 'CD0047';
update exercises set name = 'Hollow Body Hold 30 s', muscle_groups = '["Core"]'::jsonb, description = 'Múltiples series de hollow body hold isométrico de 30 s. Objetivo: Construir fuerza isométrica del tren inferior en abdominales y flexores de cadera, apoyando un trabajo de pies potente y posiciones estables en la pared. Descanso: 3 min entre series' where code = 'CD0048';
update exercises set name = 'Rutina de hombros:
- Press hombros con mancuernas
- Encogimiento de hombro inclinado
- Rotación hombro', muscle_groups = '["Hombro"]'::jsonb, description = 'Hombros a Prueba de Balas: un entrenamiento de empuje con varios ejercicios y múltiples series de cada uno. Objetivo: Desarrollar fuerza de empuje equilibrada, manteniendo el equilibrio muscular alrededor de los hombros y reduciendo el riesgo de lesión por la naturaleza dominante de tracción de la escalada. Descanso: 2 min entre series' where code = 'CD0049';
update exercises set name = 'Bloqueo 90 - 10 s', muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb, description = 'Múltiples series de lock offs isométricos de 10 s. Objetivo: Construir fuerza isométrica máxima de tracción en dorsales, bíceps y antebrazos, transfiriendose directamente a la capacidad de lock off en la pared. Descanso: 3 min entre series' where code = 'CD0050';
update exercises set name = 'Bloqueo 90 a Un Brazo - 10 s', muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb, description = 'Múltiples series de lock offs isométricos a un brazo de 10 s. Objetivo: Construir fuerza isométrica máxima de tracción en dorsales, bíceps y antebrazos, transfiriendose directamente a la capacidad de lock off en la pared. Descanso: 3 min entre series' where code = 'CD0051';
update exercises set name = 'Bloqueo 90 de Densidad: 
- Bloqueo 90
- Bloqueo 90 supino', muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb, description = 'Lock Offs de Densidad: un entrenamiento de tracción con varios ejercicios y múltiples series de cada uno. Objetivo: Desarrollar fuerza de tracción equilibrada en múltiples patrones de movimiento, construyendo la fuerza del tren superior esencial para la escalada. Descanso: 3 min entre series' where code = 'CD0052';
update exercises set name = 'Dominadas Negativas', muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb, description = 'Realiza negativas dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en dorsales, bíceps y antebrazos, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0053';
update exercises set name = 'Dominadas Negativas con peso', muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb, description = 'Este entrenamiento se centra en negativas dentro de un estímulo de fuerza máxima. Objetivo: Reclutar la fuerza de tracción máxima en dorsales, bíceps y antebrazos, construyendo la fuerza de alto nivel necesaria para movimientos potentes en terreno vertical pronunciado. Descanso: 3 min entre series' where code = 'CD0054';
update exercises set name = 'dominadas Negativas a Un Brazo', muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb, description = 'Completa las negativas a un brazo dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en dorsales, bíceps y antebrazos, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0055';
update exercises set name = 'Dominadas Negativas a Un Brazo con peso', muscle_groups = '["Espalda","Bíceps","Antebrazo"]'::jsonb, description = 'Completaras las negativas a un brazo dentro de un estímulo de fuerza máxima. Objetivo: Reclutar la fuerza de tracción máxima en dorsales, bíceps y antebrazos, construyendo la fuerza de alto nivel necesaria para movimientos potentes en terreno vertical pronunciado. Descanso: 3 min entre series' where code = 'CD0056';
update exercises set name = 'Patada de Tríceps', muscle_groups = '["Tríceps"]'::jsonb, description = 'Realiza patada de tríceps dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en tríceps, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0057';
update exercises set name = 'Peso Muerto', muscle_groups = '["Espalda","Piernas"]'::jsonb, description = 'Realiza peso muerto dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza del tren inferior en isquiotibiales, glúteos, zona lumbar y cuádriceps, mejorando tu capacidad de generar fuerza a través de pies y piernas mientras escalas. Descanso: 3 min entre series' where code = 'CD0058';
update exercises set name = 'Plancha Copenhague 30 s', muscle_groups = '["Core"]'::jsonb, description = 'Múltiples series de plancha Copenhague isométrica de 30 s. Objetivo: Construir fuerza isométrica del tren inferior en abdominales y estabilizadores profundos del core, apoyando un trabajo de pies potente y posiciones estables en la pared. Descanso: 3 min entre series' where code = 'CD0059';
update exercises set name = 'Powerlifting:
- Peso muerto
- Back squat
- Press banca', muscle_groups = '["Espalda","Piernas"]'::jsonb, description = 'Powerlifting: un entrenamiento de tren inferior con varios ejercicios y múltiples series de cada uno. Objetivo: Construir fuerza y potencia del tren inferior de forma completa, apoyando un trabajo de pies fuerte, movimiento dinámico y prevención de lesiones para la escalada. Descanso: 3 min entre series' where code = 'CD0060';
update exercises set name = 'Press hombro', muscle_groups = '["Hombro"]'::jsonb, description = 'Este entrenamiento se centra en el press Arnold dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en deltoides anterior, lateral y posterior, tríceps y pecho superior, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0061';
update exercises set name = 'Press Banca', muscle_groups = '["Pecho"]'::jsonb, description = 'Realiza press de banca dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en pecho, tríceps y deltoides anteriores, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0062';
update exercises set name = 'Press de Hombro con Mancuernas - Fuerza', muscle_groups = '["Hombro"]'::jsonb, description = 'Completaras el press de hombro con mancuernas dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en deltoides, tríceps y pecho superior, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0063';
update exercises set name = 'Press de pecho con mancuernas', muscle_groups = '["Pecho"]'::jsonb, description = 'Realiza press de pecho dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en pecho, tríceps y deltoides anteriores, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0064';
update exercises set name = 'Push up Inclinado', muscle_groups = '["Pecho"]'::jsonb, description = 'Completaras el press de pecho inclinado dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en pecho superior, tríceps y deltoides anteriores, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0065';
update exercises set name = 'Push press con kettlebell', muscle_groups = '["Hombro","Tríceps","Piernas"]'::jsonb, description = 'Este entrenamiento se centra en el press de pesa rusa invertida dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en deltoides, tríceps, antebrazos y core, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0066';
update exercises set name = 'Pseudo push up', muscle_groups = '["Pecho","Tríceps","Hombro"]'::jsonb, description = 'Completa flexiones dentro de un estímulo de fuerza. Objetivo: La fuerza de empuje repetible y exigente proviene de entrenar en este rango. Con los hombros y el serrato involucrados en el movimiento por la inclinación hacia adelante, desarrollas la fuerza detras del press en placa, los tirones de gastón y el empuje dominado por el hombro en terreno técnico. Descanso: 3 min entre series' where code = 'CD0067';
update exercises set name = 'Puente de Glúteos', muscle_groups = '["Cadera","Piernas"]'::jsonb, description = 'Completaras el puente de glúteos dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza del tren inferior en glúteos e isquiotibiales, mejorando tu capacidad de generar fuerza a través de pies y piernas mientras escalas. Descanso: 3 min entre series' where code = 'CD0068';
update exercises set name = 'Pullover de Dorsales', muscle_groups = '["Espalda"]'::jsonb, description = 'Completaras el pullover de dorsales dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en dorsales y pecho, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0069';
update exercises set name = 'Push Press con Barra', muscle_groups = '["Hombro","Tríceps","Piernas"]'::jsonb, description = 'Completa el push press con barra dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en cuádriceps, glúteos, deltoides, tríceps y core, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0070';
update exercises set name = 'Rack Pull', muscle_groups = '["Espalda","Piernas"]'::jsonb, description = 'Este entrenamiento se centra en el rack pull dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza del tren inferior en espalda alta, trapecios y antebrazos, mejorando tu capacidad de generar fuerza a través de pies y piernas mientras escalas. Descanso: 3 min entre series' where code = 'CD0071';
update exercises set name = 'Remo TRX', muscle_groups = '["Espalda"]'::jsonb, description = 'Completaras remo arquero dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en dorsales, romboides y bíceps, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0072';
update exercises set name = 'Remo con mancuerna', muscle_groups = '["Espalda"]'::jsonb, description = 'Completaras el remo bajo dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en dorsales, romboides y trapecio inferior, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0073';
update exercises set name = 'Remo Colgado en barra (horizontal)', muscle_groups = '["Espalda"]'::jsonb, description = 'Completaras el remo colgado dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en dorsales, romboides y bíceps, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0074';
update exercises set name = 'Remo Inclinado con barra', muscle_groups = '["Espalda"]'::jsonb, description = 'Este entrenamiento se centra en remo inclinado dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en dorsales, romboides y bíceps, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0075';
update exercises set name = 'Pussh press con mancuerna', muscle_groups = '["Espalda","Hombro"]'::jsonb, description = 'Completaras la retracción escapular con mancuerna dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en romboides y trapecio medio, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0076';
update exercises set name = 'Rotaciones de Hombro con Banda', muscle_groups = '["Hombro"]'::jsonb, description = 'Realiza rotaciones de hombro con banda dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en el manguito rotador y estabilizadores del hombro, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0077';
update exercises set name = 'Rotaciones de Hombro en Prono', muscle_groups = '["Hombro"]'::jsonb, description = 'Completa rotaciones de hombro en prono dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en el manguito rotador y deltoides posteriores, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0078';
update exercises set name = 'Rotaciones de Hombro Sentado', muscle_groups = '["Hombro"]'::jsonb, description = 'Realiza rotaciones de hombro sentado dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en el manguito rotador y estabilizadores del hombro, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0079';
update exercises set name = 'Rutina de Calistenia:
- Sentadilla sumo 
- Estocada profunda con rotación
- I a W boca abajo
- Contracción escapular en plancha
- Lumbares
- Puente gluteo
- Push up
- L sit sentado
- Superman en plancha', muscle_groups = '["Pecho","Core"]'::jsonb, description = 'Completa un circuito de calistenia de 10 minutos trabajando cada ejercicio con un tempo de 30 segundos activo, 30 segundos de descanso. Objetivo: Esta rutina guiada de calistenia de 10 minutos para escaladores cubre todas las bases. Funciona como un calentamiento completo de cuerpo entero antes de una sesión de escalada exigente, o como entrenamiento minimalista independiente cuando estas en movimiento. El circuito esta diseñado específicamente para mejorar la tensión corporal, la movilidad de cadera y la estabilidad del hombro, sin necesidad de gimnasio. Descanso: 30 segundos' where code = 'CD0080';
update exercises set name = 'Secuencia TRX IYT en Prono', muscle_groups = '["Espalda","Hombro"]'::jsonb, description = 'Completaras la secuencia TRX IYT en prono dentro de un estímulo de repeticiones moderadas. Objetivo: Desarrollar fuerza de empuje en deltoides posteriores, trapecio inferior y manguito rotador, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0081';
update exercises set name = 'Secuencia TRX IYT en Supino', muscle_groups = '["Espalda","Hombro"]'::jsonb, description = 'Este entrenamiento se centra en la secuencia TRX IYT en supino dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en deltoides posteriores, trapecio inferior y manguito rotador, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0082';
update exercises set name = 'Sentadilla Goblet', muscle_groups = '["Piernas"]'::jsonb, description = 'Realiza sentadilla goblet dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza del tren inferior en cuádriceps, glúteos y core, mejorando tu capacidad de generar fuerza a través de pies y piernas mientras escalas. Descanso: 3 min entre series' where code = 'CD0083';
update exercises set name = 'Back squat', muscle_groups = '["Piernas"]'::jsonb, description = 'Completa la sentadilla trasera dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza del tren inferior en cuádriceps, isquiotibiales, glúteos y zona lumbar, mejorando tu capacidad de generar fuerza a través de pies y piernas mientras escalas. Descanso: 3 min entre series' where code = 'CD0084';
update exercises set name = 'Rutina potencia de tracción:
- Dominada con peso
- Dominada explosiva', muscle_groups = '["Espalda"]'::jsonb, description = 'Superserie de Potencia de Tracción: un entrenamiento de tracción con varios ejercicios y múltiples series de cada uno. Objetivo: Desarrollar fuerza de tracción equilibrada en múltiples patrones de movimiento, construyendo la fuerza del tren superior esencial para la escalada. Descanso: 3 min entre series' where code = 'CD0085';
update exercises set name = 'Kettlebell swing', muscle_groups = '["Cadera","Piernas","Core"]'::jsonb, description = 'Este entrenamiento se centra en swings con pesa rusa dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de empuje en glúteos, isquiotibiales y core, equilibrando las demandas dominantes de tracción de la escalada y protegiendo la salud del hombro. Descanso: 3 min entre series' where code = 'CD0086';
update exercises set name = 'Dominadas anchas', muscle_groups = '["Espalda"]'::jsonb, description = 'Completaras las tracciones anchas dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza de tracción en dorsales, bíceps y antebrazos, mejorando tu capacidad de traccionar y controlar los movimientos de escalada. Descanso: 3 min entre series' where code = 'CD0087';
update exercises set name = 'Dominadas explosivas', muscle_groups = '["Espalda"]'::jsonb, description = 'Completa tracciones de potencia en varias series. Objetivo: Reclutar la fuerza de tracción máxima en dorsales, bíceps y antebrazos, construyendo la fuerza de alto nivel necesaria para movimientos potentes en terreno vertical pronunciado. Descanso: 5 min entre series' where code = 'CD0088';
update exercises set name = 'Estocada con mancuernas', muscle_groups = '["Piernas"]'::jsonb, description = 'Completa la zancada caminando con mancuernas dentro de un estímulo de fuerza. Objetivo: Desarrollar fuerza del tren inferior en cuádriceps, glúteos e isquiotibiales, mejorando tu capacidad de generar fuerza a través de pies y piernas mientras escalas. Descanso: 3 min entre series' where code = 'CD0089';
update exercises set name = 'F2 Open - Levantamiento - Fácil', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Realiza levantamientos de 7 s en agarre F2 open (front two open hand), a baja intensidad para mantener la salud del tejido en varias series. Objetivo: Mantener la carga en F2 open a baja intensidad para promover la salud del tejido y el confort sin acumular fatiga. Descanso: 60 s entre series' where code = 'FB0001';
update exercises set name = 'F2 Open - Levantamiento - Fuerza', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Realizaras levantamientos de 10 s en agarre F2 open en varias series. Objetivo: Aumentar la fuerza de dedos en F2 open mediante carga isométrica de alta intensidad a una duración desafiante pero sostenible. Descanso: 3 min entre series' where code = 'FB0002';
update exercises set name = 'F2 Open - Levantamiento - Máximo', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Realizaras levantamientos de 7 s en agarre F2 open, a intensidad casi máxima para fuerza de peak en varias series. Objetivo: Desarrollar la fuerza máxima de dedos en F2 open mediante carga isométrica corta de alta intensidad con recuperación completa. Descanso: 3 min entre series' where code = 'FB0003';
update exercises set name = 'F2 Open - Levantamiento - Peak', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Completa levantamientos de 5 s en agarre F2 open en varias series. Objetivo: Aumentar la fuerza de peak de dedos en F2 open y el reclutamiento de unidades motoras mediante esfuerzos muy cortos de intensidad máxima. Descanso: 3 min entre series' where code = 'FB0004';
update exercises set name = 'F3 Half Crimp - Levantamiento - Fuerza', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Este entrenamiento se centra en levantamientos de 10 s en agarre F3 Half crimp. Objetivo: Aumentar la fuerza de dedos en F3 Half crimp mediante carga isométrica de alta intensidad a una duración desafiante pero sostenible. Descanso: 3 min entre series' where code = 'FB0005';
update exercises set name = 'F3 Half Crimp - Levantamiento - Máximo', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Este entrenamiento se centra en levantamientos de 7 s en agarre F3 Half crimp (front three half crimp), a intensidad casi máxima para fuerza de peak. Objetivo: Desarrollar la fuerza máxima de dedos en F3 Half crimp mediante carga isométrica corta de alta intensidad con recuperación completa. Descanso: 3 min entre series' where code = 'FB0006';
update exercises set name = 'Half Crimp 4 - Levantamiento - Base', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Realiza levantamientos de 30 s en Half crimp, a intensidad moderada para construir fuerza base en varias series. Objetivo: Construir fuerza base de dedos en Half crimp mediante carga isométrica de mayor duración a intensidad moderada. Descanso: 3 min entre series' where code = 'FB0007';
update exercises set name = 'Half Crimp 4 - Levantamiento - Fuerza', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Este entrenamiento se centra en levantamientos de 10 s en Half crimp, dentro de un estímulo de fuerza. Objetivo: Aumentar la fuerza de dedos en Half crimp mediante carga isométrica de alta intensidad a una duración desafiante pero sostenible. Descanso: 3 min entre series' where code = 'FB0008';
update exercises set name = 'Half Crimp 4 - Levantamiento - Máximo', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Este entrenamiento se centra en levantamientos de 7 s en Half crimp, a intensidad casi máxima para fuerza de peak. Objetivo: Desarrollar la fuerza máxima de dedos en Half crimp mediante carga isométrica corta de alta intensidad con recuperación completa. Descanso: 3 min entre series' where code = 'FB0009';
update exercises set name = 'Half Crimp 4 - Levantamiento - Test Máximo', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Testea tus límites aumentando progresivamente hasta tu máximo de 7 s en varios levantamientos de Half crimp (intensidad máxima). Objetivo: Establecer tu máximo actual para la duración de sujeción prescrita, guiando la intensidad de entrenamiento futura. Descanso: 3 min entre series' where code = 'FB0010';
update exercises set name = 'Half Crimp 4 - Repeticiones - Fuerza', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Completa repeticiones de contrae y relaja en Half crimp, dentro de un estímulo de fuerza usando un protocolo de repeticiones más corto. Objetivo: Aumentar la fuerza de dedos en Half crimp mediante contracciones repetidas de alta intensidad en lugar de sujeciones sostenidas. Descanso: 3 min entre series' where code = 'FB0011';
update exercises set name = 'Levantamientos de Reclutamiento de Flexores de Dedos', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Completaras múltiples series de levantamientos, aumentando progresivamente la intensidad de muy fácil a desafiante. Objetivo: Calentar y reclutar los flexores de dedos antes de un entrenamiento de escalada aumentando gradualmente la carga. Descanso: 2 min entre series' where code = 'FB0012';
update exercises set name = 'M2 Open - Levantamiento - Fácil', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Completa levantamientos de 7 s en agarre M2 open (middle two open hand), a baja intensidad para mantener la salud del tejido en varias series. Objetivo: Mantener la carga en M2 open a baja intensidad para promover la salud del tejido y el confort sin acumular fatiga. Descanso: 60 s entre series' where code = 'FB0013';
update exercises set name = 'M2 Open - Levantamiento - Fuerza', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Realiza levantamientos de 10 s en agarre M2 open en varias series. Objetivo: Aumentar la fuerza de dedos en M2 open mediante carga isométrica de alta intensidad a una duración desafiante pero sostenible. Descanso: 3 min entre series' where code = 'FB0014';
update exercises set name = 'M2 Open - Levantamiento - Máximo', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Realiza levantamientos de 7 s en agarre M2 open, a intensidad casi máxima para fuerza de peak en varias series. Objetivo: Desarrollar la fuerza máxima de dedos en M2 open mediante carga isométrica corta de alta intensidad con recuperación completa. Descanso: 3 min entre series' where code = 'FB0015';
update exercises set name = 'M2 Open - Levantamiento - Peak', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Este entrenamiento se centra en levantamientos de 5 s en agarre M2 open. Objetivo: Aumentar la fuerza de peak de dedos en M2 open y el reclutamiento de unidades motoras mediante esfuerzos muy cortos de intensidad máxima. Descanso: 3 min entre series' where code = 'FB0016';
update exercises set name = 'Aductores de Cadera', muscle_groups = '["Movilidad general","Cadera","Piernas"]'::jsonb, description = 'Un entrenamiento guiado de mariposa, split lateral ISO, rana y medio split lateral para aumentar la flexibilidad de los aductores de cadera. Objetivo: Mejorar el alcance lateral de la pierna aumentando la flexibilidad de los aductores, ampliando las opciones de presas de pie y la economía de movimiento en la pared. Descanso: 60 s entre series' where code = 'FL0001';
update exercises set name = 'Calentamiento:
- Rotación interna de rodilla
- Pigeon pose
- Izquiotibial a ambos lados (sentado)
- Posición caballo
- Ranita
- Elongación gemelos', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Una rutina guiada rápida de rotación interna acostado, postura de paloma, estiramiento de isquiotibiales, postura de caballo ISO, rana y estiramiento de gemelo para uso de calentamiento o vuelta a la calma. Objetivo: Mantener la flexibilidad del tren inferior y preparar las articulaciones para la escalada, adecuado como calentamiento previo al entrenamiento o vuelta a la calma posterior.' where code = 'FL0002';
update exercises set name = 'Dislocaciones de Hombro', muscle_groups = '["Movilidad general","Hombro"]'::jsonb, description = 'Realiza pases circulares de hombro usando un palo o banda, siguiendo un tempo para guiar el movimiento a través del rango completo. Objetivo: Aumentar la movilidad de hombro y el rango por encima de la cabeza mediante trabajo de tempo controlado, mejorando el alcance y la libertad de movimiento en la pared. Descanso: 60 s entre series' where code = 'FL0003';
update exercises set name = 'Elevación de pierna en Barra - ISO', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Realiza elevaciones laterales de pierna controladas para fortalecer los abductores de cadera cerca de su rango final de movimiento. Objetivo: Construir fuerza del abductor de cadera en el rango final, mejorando la elevación lateral activa de la pierna para colocaciones de pie amplias mientras escalas. Descanso: 60 s entre series' where code = 'FL0004';
update exercises set name = 'Estiramiento de Bíceps - Estático Pasivo', muscle_groups = '["Movilidad general","Bíceps"]'::jsonb, description = 'Manten un estiramiento estático de bíceps usando la posición de tu cuerpo para sostener el estiramiento durante sujeciones cronometradas. Objetivo: Mejorar la flexibilidad de bíceps y codo, reduciendo la rigidez de la escalada y apoyando la extensión completa del brazo en la pared. Descanso: 60 s entre series' where code = 'FL0005';
update exercises set name = 'Estiramiento de Cuádriceps - Sentado - Estático Pasivo', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Manten un estiramiento pasivo de cuádriceps en posición sentada, reclinandote hacia atrás para aumentar y sostener el estiramiento durante sujeciones cronometradas. Objetivo: Alargar los cuádriceps y flexores de cadera mediante sujeciones pasivas, mejorando el rango de flexión de rodilla y extensión de cadera para heel hooks y pasos altos. Descanso: 60 s entre series' where code = 'FL0006';
update exercises set name = 'Estiramiento de Flexor de Cadera en Pared - Estático Pasivo', muscle_groups = '["Movilidad general","Cadera","Piernas"]'::jsonb, description = 'Manten un estiramiento pasivo de flexor de cadera y cuádriceps usando una pared para profundizar el estiramiento durante sujeciones cronometradas. Objetivo: Alargar los flexores de cadera y cuádriceps, mejorando el rango de extensión de cadera para pasos altos, mantle y escalada en pared pronunciada. Descanso: 60 s entre series' where code = 'FL0007';
update exercises set name = 'Estiramiento de Gemelo en Pared - Estático Pasivo', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Manten un estiramiento pasivo de gemelo usando una pared para sostener la posición de estiramiento durante sujeciones cronometradas. Objetivo: Mejorar la flexibilidad de gemelo y tobillo, permitiendo bajadas de talón más profundas y mejor contacto de pie en las presas de pie. Descanso: 60 s entre series' where code = 'FL0008';
update exercises set name = 'Estiramiento de Isquiotibiales - Sentado - Estático Pasivo', muscle_groups = '["Movilidad general","Cadera","Piernas"]'::jsonb, description = 'Manten un estiramiento de isquiotibiales sentado usando la posición del cuerpo y la gravedad para sostener el estiramiento durante sujeciones cronometradas. Objetivo: Aumentar la flexibilidad de isquiotibiales mediante sujeciones pasivas sostenidas, mejorando el rango de flexión de tronco para heel hooks y colocaciones de pie alto. Descanso: 60 s entre series' where code = 'FL0009';
update exercises set name = 'Estiramiento de Muñeca - Estático Pasivo', muscle_groups = '["Movilidad general","Muñeca"]'::jsonb, description = 'Múltiples series de estiramiento de muñeca pasivo de 60 s. Objetivo: Mejorar la flexibilidad de flexores y extensores de muñeca, apoyando la salud de los dedos y reduciendo el riesgo de lesión por las altas demandas de carga de la escalada. Descanso: 60 s entre series' where code = 'FL0010';
update exercises set name = 'Estiramiento de Pecho - Estático Pasivo', muscle_groups = '["Movilidad general","Pecho"]'::jsonb, description = 'Manten un estiramiento pasivo de pecho usando la gravedad o una superficie externa para sostener la posición de apertura del pecho durante sujeciones cronometradas. Objetivo: Mejorar la flexibilidad de pecho y hombro anterior, reduciendo la rigidez de la escalada y apoyando posiciones de cuerpo abierto en la pared. Descanso: 60 s entre series' where code = 'FL0011';
update exercises set name = 'Estiramiento Revolver - Estático Pasivo', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Manten un estiramiento revolver pasivo en medio split para estirar los dorsales y el costado del torso durante sujeciones cronometradas. Objetivo: Aumentar la flexibilidad de dorsales y tronco lateral, mejorando el alcance lateral y el movimiento por encima de la cabeza en la pared. Descanso: 60 s entre series' where code = 'FL0012';
update exercises set name = 'Estiramiento Sleeper - Estático Pasivo', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Manten un estiramiento sleeper acostado de lado, usando la gravedad y el otro brazo para sostener un estiramiento posterior del hombro durante sujeciones cronometradas. Objetivo: Mejorar la flexibilidad posterior del hombro y el rango de rotación interna, reduciendo la rigidez del hombro por la escalada y apoyando una mecanica articular saludable. Descanso: 60 s entre series' where code = 'FL0013';
update exercises set name = 'Estiramientos de Dedos - Estático Pasivo', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Múltiples series de estiramientos de dedos pasivos de 60 s. Objetivo: Mejorar la flexibilidad de flexores y extensores de los dedos, apoyando la salud de los dedos y reduciendo el riesgo de lesión por las altas demandas de carga de la escalada. Descanso: 60 s entre series' where code = 'FL0014';
update exercises set name = 'Fire Hydrant - Pierna Flexionada - Desarrollo de Fuerza', muscle_groups = '["Movilidad general","Pecho","Tríceps","Hombro"]'::jsonb, description = 'Realiza repeticiones de fire hydrant con pierna flexionada para fortalecer los glúteos y los rotadores externos de cadera cerca del rango final de movimiento. Objetivo: Construir fuerza de glúteos y rotadores de cadera en el rango final, mejorando la estabilidad y el control en posiciones de escalada con rotación externa. Descanso: 1 min 30 s entre series' where code = 'FL0015';
update exercises set name = 'Flexibilidad de Antebrazo', muscle_groups = '["Movilidad general","Antebrazo"]'::jsonb, description = 'Un entrenamiento guiado de estiramientos de extensores y flexores de muñeca para aumentar la flexibilidad de antebrazo y muñeca. Objetivo: Mejorar el rango de movimiento de muñeca y antebrazo, apoyando una mayor variedad de posiciones de presa incluyendo undercuts, gastones y regletas planas. Descanso: 30 s entre series' where code = 'FL0016';
update exercises set name = 'Flexibilidad de Tobillo', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Un entrenamiento guiado de estiramientos de gemelos, elevaciones de talón tipo burro y estiramientos de pescador para aumentar el rango de movimiento del tobillo. Objetivo: Mejorar la dorsiflexión del tobillo para que puedas bajar más el talón en las presas de pie, aumentando el área de contacto y la fricción para escalada en placa y vertical. Descanso: 60 s entre series' where code = 'FL0017';
update exercises set name = 'Glúteos e Isquiotibiales', muscle_groups = '["Movilidad general","Cadera","Piernas"]'::jsonb, description = 'Un entrenamiento guiado de estiramiento de sofá, pancake de pie, postura de paloma y split lateral ISO para aumentar la flexibilidad de glúteos e isquiotibiales. Objetivo: Mejorar el rango de cadera, glúteo e isquiotibial para que puedas colocar los pies más alto en la pared manteniendo las caderas cerca, aumentando la economía de movimiento. Descanso: 60 s entre series' where code = 'FL0018';
update exercises set name = 'Good Morning Sentado - Estiramiento con Tempo', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Realiza good mornings sentado siguiendo un temporizador de tempo a través de las fases de bajada, pausa y subida para estirar los isquiotibiales. Objetivo: Mejorar la flexibilidad de isquiotibiales y el rango de flexión de tronco mediante trabajo de tempo controlado, apoyando los heel hooks y las colocaciones de pie alto. Descanso: 1 min 30 s entre series' where code = 'FL0019';
update exercises set name = 'Mantenimiento de Flexibilidad', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Una rutina guiada de mantenimiento de cuerpo entero con patadas, pancake, rana, paloma, estiramiento de sofá, estiramiento de gemelo, estiramiento de pecho y estiramiento de dorsal a baja intensidad. Objetivo: Mantener las ganancias de flexibilidad durante semanas de descarga y taper, previniendo la regresión del rango de movimiento sin agregar carga de entrenamiento. Descanso: 5 s entre series' where code = 'FL0020';
update exercises set name = 'Movilidad Matutina', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Un entrenamiento guiado diario en el piso de giro de sabio, postura de cachorro, estiramiento de gemelo en pared, side runner, postura de paloma y sentadilla yogui para movilidad de cuerpo entero. Objetivo: Construir movilidad mediante la práctica diaria de baja intensidad, reforzando el hábito para apoyar las ganancias de flexibilidad con el tiempo. Descanso: 30 s entre series' where code = 'FL0021';
update exercises set name = 'Pancake - De Pie - Estático Pasivo', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Manten un estiramiento de pancake de pie con las piernas bien separadas, usando la gravedad para asistir el pliegue hacia adelante durante sujeciones cronometradas. Objetivo: Aumentar la flexibilidad de isquiotibiales y aductores en una posición de piernas opens de pie, apoyando el movimiento de piernas amplias y los pasos altos mientras escalas. Descanso: 60 s entre series' where code = 'FL0022';
update exercises set name = 'Pancake - Pulsos', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Pulsa hacia un estiramiento profundo de pancake, moviendote a través del arco de tu posición de piernas opens por repeticiones. Objetivo: Aumentar la flexibilidad de isquiotibiales y aductores mediante pulsos dinámicos, mejorando el rango de piernas opens para colocaciones de pie amplias. Descanso: 1 min 30 s entre series' where code = 'FL0023';
update exercises set name = 'Patadas Frontales - Dinámico', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Realiza patadas frontales controladas para estirar activamente los isquiotibiales y flexores de cadera. Objetivo: Construir flexibilidad dinámica de isquiotibiales y potencia de flexores de cadera, mejorando la capacidad de levantar los pies alto frente al cuerpo mientras escalas. Descanso: 60 s entre series' where code = 'FL0024';
update exercises set name = 'Patadas Laterales - Dinámico', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Realiza patadas laterales controladas para estirar activamente los aductores de cadera a través de su rango completo. Objetivo: Desarrollar rango de movimiento lateral dinámico de cadera, mejorando la capacidad de colocar los pies amplios con control mientras escalas. Descanso: 60 s entre series' where code = 'FL0025';
update exercises set name = 'Peso Muerto Rumano a Una Pierna - Estiramiento con Tempo', muscle_groups = '["Movilidad general","Espalda","Piernas"]'::jsonb, description = 'Realiza peso muerto rumano a una pierna siguiendo un temporizador de tempo a través de las fases de bajada, pausa y subida para estirar los isquiotibiales. Objetivo: Aumentar la flexibilidad de isquiotibiales a una pierna mediante trabajo de tempo controlado, mejorando el rango de pliegue hacia adelante y la capacidad de heel hook. Descanso: 1 min 30 s entre series' where code = 'FL0026';
update exercises set name = 'Postura de Caballo - ISO - Estático Activo', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Manten una posición de sentadilla de caballo en profundidad mientras usas activamente tus músculos para mantener la postura durante sujeciones cronometradas. Objetivo: Construir flexibilidad de aductores y estabilidad de cadera mediante sujeciones activas, mejorando la capacidad de mantener posturas amplias en la pared. Descanso: 60 s entre series' where code = 'FL0027';
update exercises set name = 'Postura de Paloma - Contrae y Relaja', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Alterna entre contraer y relajar los músculos de la cadera en una postura de paloma para facilitar un estiramiento más profundo con cada ciclo. Objetivo: Mejorar la flexibilidad de glúteo y rotador de cadera usando técnicas FNP, acelerando las ganancias en la rotación externa de cadera para la técnica de escalada. Descanso: 60 s entre series' where code = 'FL0028';
update exercises set name = 'Pullover de Dorsales con Mancuerna - Estiramiento con Tempo', muscle_groups = '["Movilidad general","Espalda"]'::jsonb, description = 'Realiza pullovers de dorsales con mancuerna siguiendo un temporizador a través de las fases de bajada, pausa y subida para estirar los dorsales y los hombros. Objetivo: Aumentar la flexibilidad por encima de la cabeza de dorsales y hombros mediante trabajo de tempo cargado, mejorando el alcance y el movimiento por encima de la cabeza en la pared. Descanso: 1 min 30 s entre series' where code = 'FL0029';
update exercises set name = 'Pulsos de Split Frontal - Dinámico', muscle_groups = '["Movilidad general","Piernas"]'::jsonb, description = 'Realiza repeticiones de pulso controladas manteniendo una profundidad exigente de split frontal para fortalecer los músculos en el rango final. Objetivo: Desarrollar fuerza activa y resistencia muscular a una profundidad de split casi máxima, construyendo rango utilizable para posiciones de escalada. Descanso: 60 s entre series' where code = 'FL0030';
update exercises set name = 'Pulsos y Patadas', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Un entrenamiento guiado diario de patadas laterales, patadas frontales y pulsos de pancake para entrenar la flexibilidad dinámica mediante repetición de alta frecuencia. Objetivo: Desarrollar rango activo dinámico mediante ejercicios diarios de patadas y pulsos, construyendo flexibilidad utilizable para el movimiento de escalada.' where code = 'FL0031';
update exercises set name = 'Rana Supina - Estático Pasivo', muscle_groups = '["Movilidad general"]'::jsonb, description = 'Manten un estiramiento de rana acostado boca arriba, usando la gravedad para asistir la apertura de cadera durante sujeciones cronometradas. Objetivo: Aumentar la flexibilidad de aductores de cadera en una posición asistida, construyendo rango de ingle para posiciones de escalada con piernas opens. Descanso: 60 s entre series' where code = 'FL0032';
update exercises set name = 'Rotación Externa con Banda - Contrae y Relaja', muscle_groups = '["Movilidad general","Hombro"]'::jsonb, description = 'Múltiples series de ciclos de contrae y relaja. Objetivo: Usar técnicas de contrae y relaja para mejorar el rango de movimiento en el manguito rotador y el hombro posterior, mejorando la calidad del movimiento y la salud del hombro para la escalada. Descanso: 1 min 30 s entre series' where code = 'FL0033';
update exercises set name = 'Sentadillas Cosaco - Estiramiento con Tempo', muscle_groups = '["Movilidad general","Piernas"]'::jsonb, description = 'Realiza sentadillas cosaco siguiendo un temporizador de tempo a través de las fases de bajada, pausa y subida para estirar los aductores y las caderas. Objetivo: Desarrollar movilidad lateral de cadera y flexibilidad de aductores bajo control, mejorando la capacidad de alcanzar presas de pie amplias. Descanso: 1 min 30 s entre series' where code = 'FL0034';
update exercises set name = 'Sentadillas Split - Estiramiento con Tempo', muscle_groups = '["Movilidad general","Piernas"]'::jsonb, description = 'Realiza sentadillas split siguiendo un temporizador de tempo a través de las fases de bajada, pausa y subida para estirar los flexores de cadera y cuádriceps. Objetivo: Desarrollar la longitud del flexor de cadera y la flexibilidad de cuádriceps bajo carga, mejorando la zancada profunda y la capacidad de paso alto en la pared. Descanso: 1 min 30 s entre series' where code = 'FL0035';
update exercises set name = 'Split Frontal - Nivel 1', muscle_groups = '["Movilidad general","Piernas"]'::jsonb, description = 'Un entrenamiento de split frontal con varios ejercicios usando peso muerto rumano a una pierna y sujeciones isométricas de zancada larga para desarrollar fuerza y rango mediante estiramientos activo-estáticos. Objetivo: Construir flexibilidad de isquiotibiales y flexores de cadera con fuerza en el rango final, creando una base para la progresión del split frontal y la capacidad de paso alto.' where code = 'FL0036';
update exercises set name = 'Split Lateral - Nivel 1', muscle_groups = '["Movilidad general","Piernas"]'::jsonb, description = 'Un entrenamiento guiado de split lateral usando sujeciones ISO de postura de caballo y estiramientos de pancake de pie para desarrollar fuerza y rango de aductores de cadera mediante trabajo activo y estático. Objetivo: Construir rango de split lateral fundamental y fuerza de aductores sin carga externa, creando una base para una mayor progresión de flexibilidad. Descanso: 10 s entre series' where code = 'FL0037';
update exercises set name = 'Split Lateral ISO - Estático Activo', muscle_groups = '["Movilidad general","Piernas"]'::jsonb, description = 'Manten una posición de split lateral mientras involucras activamente tus músculos para sostener el estiramiento durante sujeciones cronometradas. Objetivo: Construir fuerza activa y control a la profundidad del split lateral, desarrollando rango de movimiento utilizable para posiciones de escalada amplias. Descanso: 60 s entre series' where code = 'FL0038';
update exercises set name = 'Test de Split Lateral - Sin Apoyo', muscle_groups = '["Movilidad general","Piernas"]'::jsonb, description = 'Realiza una sujeción ISO de split lateral sin apoyo para registrar tu rendimiento actual de split lateral, con notas y medidas registradas en el tiempo. Objetivo: Establecer una referencia de tu progreso en split lateral mediante un test estandarizado, permitiendote a ti y a tu entrenador seguir las ganancias de flexibilidad en el tiempo.' where code = 'FL0039';
update exercises set name = 'Zancada Larga ISO - Estático Pasivo', muscle_groups = '["Movilidad general","Piernas"]'::jsonb, description = 'Manten una posición de zancada larga de forma pasiva, usando la posición del cuerpo y la gravedad para sostener el estiramiento del flexor de cadera durante sujeciones cronometradas. Objetivo: Alargar los flexores de cadera mediante sujeciones pasivas sostenidas, mejorando el rango de extensión de cadera para pasos altos y posiciones de pared pronunciada. Descanso: 60 s entre series' where code = 'FL0040';
update exercises set name = '30 Movimientos Fraccionados', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Divide una ruta o circuito de 30 movimientos en 3 secciones de 10 movimientos, descansando 20 segundos entre secciones. Descansa 6 minutos entre vueltas completas. Objetivo: Entrenar el rendimiento en escalada sostenida dividiendo una ruta de nivel límite en secciones completables. Descanso: 6 min entre series' where code = 'PE0001';
update exercises set name = '4x4', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Escala 4 boulders seguidos con poco o ningun descanso entre problemas, luego descansa antes de repetir durante varias series. Objetivo: Desarrollar la potencia aeróbica mediante esfuerzos de alta intensidad con descanso limitado, usando movimiento variado de boulder para impulsar el rendimiento sostenido. Descanso: 5 min entre series' where code = 'PE0002';
update exercises set name = '5 Series Más Difíciles', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Escala 5 rutas o circuitos difíciles de 30-40 movimientos de más fácil a más difícil. Objetivo: Mejorar la potencia aeróbica mediante esfuerzos de longitud de ruta desafiantes que te preparan para las demandas de la escalada deportiva difícil. Descanso: 10 min entre series' where code = 'PE0003';
update exercises set name = '6 en 6', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Completa 6 boulders al minuto en varias series. El marco de tiempo comprimido genera fatiga rápida. Objetivo: Desarrollar producción anaeróbica repetida con cada boulder completado al minuto. Descanso: 5 min entre series' where code = 'PE0004';
update exercises set name = 'A Vista', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Intenta 4 rutas en o cerca de tu nivel a vista de punta, dedicando tiempo a leer la ruta y prepararte antes de cada intento unico. Objetivo: Entrenar la potencia aeróbica junto con las habilidades tácticas y psicológicas necesarias para rendir en intentos a vista. Descanso: 20 min entre series' where code = 'PE0005';
update exercises set name = 'Boulders Enlazados', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Repite un boulder largo bien ensayado (alrededor de 14 movimientos) en varias series. Objetivo: Mejorar la tolerancia a secuencias sostenidas de alta intensidad que exigen un esfuerzo prolongado. Descanso: 5 min entre series' where code = 'PE0006';
update exercises set name = 'Boulders Extendidos', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Repite un boulder largo de 16 movimientos en varias series. Espera estar luchando hacia el final. Objetivo: Impulsar la tolerancia a secuencias sostenidas de alta intensidad que conectan el boulder con el esfuerzo de la longitud de una ruta. Descanso: 5 min entre series' where code = 'PE0007';
update exercises set name = 'Boulder dobles', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Escala un boulder difícil, descanso breve, luego repitelo de inmediato. Completa varias series de dobles. Objetivo: Desarrollar la capacidad anaeróbica y la habilidad de mantener la intensidad en esfuerzos repetidos de alta potencia. Descanso: 4 min entre series' where code = 'PE0008';
update exercises set name = 'Ruta doble', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Escala una ruta difícil, descansa brevemente en la pared o baja, luego repitela de inmediato. Completa 5 vueltas dobles con descanso completo entre series. Objetivo: Construir potencia aeróbica sostenida replicando esfuerzos más largos, asegurando un alto volumen de escalada fatigante. Descanso: 10 min entre series' where code = 'PE0009';
update exercises set name = 'Boulder volumen - Intervalos Forzados', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Completa un número alto de boulders de rango medio en varias series con descansos cortos, asegurando una amplia variedad de movimiento. Objetivo: Impulsar la potencia aeróbica completando un alto volumen de boulders de intensidad media a alta bajo fatiga. Descanso: 10 min entre series' where code = 'PE0010';
update exercises set name = 'Pirámide de Rutas', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Escala 8 rutas en pirámide, empezando fácil, subiendo hasta tu nivel más difícil, y luego bajando de nuevo. Si tienes menos series, detente en la cima. Objetivo: Entrenar la potencia aeróbica completando escalada de rutas de alto volumen a través de intensidades ascendentes y descendentes. Descanso: 10 min entre series' where code = 'PE0011';
update exercises set name = 'Proyectando Rutas', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Dedica el entrenamiento a intentar rutas en el límite de tu capacidad, ya sean proyectos o escaladas nuevas difíciles. Apunta a 150-250 movimientos en total. Objetivo: Desarrollar la resistencia de potencia de alto nivel intentando rutas difíciles, construyendo la capacidad de rendir a este nivel.' where code = 'PE0012';
update exercises set name = 'Proyecto de Capacidad Anaeróbica', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Repite un boulder específico de proyecto o replica en varias series, escalando con enfoque de rendimiento. Objetivo: Transferir las ganancias de capacidad anaeróbica a las demandas reales o específicas del proyecto. Descanso: 5 min entre series' where code = 'PE0013';
update exercises set name = 'Test de Repeticiones al 60%', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Cuelgate al 60% de tu máximo a dos brazos con un ciclo de 7 segundos activo, 3 segundos de descanso, y continua hasta el fallo. Registra tu tiempo total hasta el agotamiento. Objetivo: Testear y establecer una referencia de tu capacidad de resistencia del antebrazo a una intensidad submáxima estandarizada.' where code = 'PE0014';
update exercises set name = 'Triples de Boulder', muscle_groups = '["Dedos","Antebrazo"]'::jsonb, description = 'Escala un boulder difícil 3 veces por serie con descanso corto entre repeticiones, completando varias series. Objetivo: Desarrollar la capacidad anaeróbica mediante esfuerzos repetidos de alta intensidad que acumulan fatiga a través de las repeticiones y del transcurso de la sesión. Descanso: 5 min entre series' where code = 'PE0015';
update exercises set name = 'Campus - 3 Movimientos', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Realiza 3 movimientos máximos de campus por serie en varias series, enfocandote en velocidad y contacto controlado en cada peldano. Objetivo: Aumentar la potencia de tracción máxima y la fuerza de contacto mediante secuencias de campus máximas extendidas. Descanso: 3 min entre series' where code = 'SP0001';
update exercises set name = 'Circuitos de Boulder', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Sigue un circuito o elige boulders dentro de un rango de grado dado, trabajando problemas justo por encima de tu nivel a vista con series estructuradas. Objetivo: Construir fuerza submáxima y variedad de movimiento mediante un esfuerzo consistente y repetible a través de una gama de problemas. Descanso: 6 min entre series' where code = 'SP0002';
update exercises set name = 'Eficiencia en Board', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Refina la beta y elimina movimientos innecesarios en problemas de board que ya conoces. Enfocate en escalar de la manera más limpia y eficiente posible. Objetivo: Aumentar la eficiencia técnica y la economía energética en terreno vertical pronunciado sin necesidad de ganar fuerza.' where code = 'SP0003';
update exercises set name = 'Eliminados', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Escala problemas con presas eliminadas para forzar soluciones creativas y dinámicas. Adopta la resolución de problemas y el movimiento poco familiar. Objetivo: Desarrollar coordinación, precisión y adaptabilidad mediante escalada restringida. Descanso: 2 min entre series' where code = 'SP0004';
update exercises set name = 'Encadenando a Vista (Flash)', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Comprometete por completo con esfuerzos de un solo intento a vista (flash) en problemas de tu grado de flash a través de una variedad de estilos. Lee la ruta con cuidado, luego da el 100%. Objetivo: Mejorar la capacidad de flash, la toma de decisiones y la ejecución bajo alta presión. Descanso: 3 min entre series' where code = 'SP0005';
update exercises set name = 'Boulder send', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Intenta problemas que sean difíciles pero alcanzables en pocos intentos. Prioriza los encadenes exitosos y la ejecución precisa. Objetivo: Reforzar la consistencia de rendimiento mientras se construye fuerza y potencia submáxima.' where code = 'SP0006';
update exercises set name = 'Board send', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Intenta problemas de board justo por debajo de tu límite que puedas completar en pocos intentos. Apunta a encadenes de calidad más que a proyectos de largo plazo. Objetivo: Construir confianza y capacidad de rendimiento en terreno de board pronunciado mediante la ejecución exitosa de problemas difíciles.' where code = 'SP0007';
update exercises set name = 'Boulder foco', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Enfocate en un tema técnico o estilo de movimiento específico durante todo el entrenamiento, según indique tu entrenador. Ejecuta con precisión. Objetivo: Abordar debilidades técnicas individuales mientras se mantiene un estímulo de fuerza. Descanso: 3 min entre series' where code = 'SP0008';
update exercises set name = 'Esfuerzos Máximos de Boulder', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Intenta problemas de boulder en el límite de tu capacidad con recuperación completa entre intentos. Los problemas pueden tomar varios entrenamientos completar. Objetivo: Aumentar la fuerza máxima y la producción de potencia.' where code = 'SP0009';
update exercises set name = 'Esfuerzos Máximos de Boulder Sin Pies', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Campusea los problemas de boulder de 4 movimientos más difíciles posibles en presas grandes sin usar los pies. Usa movimientos potentes y evita los lock offs estáticos. Objetivo: Aumentar la fuerza de tracción, la tensión y la precisión a intensidad máxima sin asistencia del tren inferior. Descanso: 10 min entre series' where code = 'SP0010';
update exercises set name = 'Esfuerzos Máximos en Board', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Trabaja a verdadera intensidad de alto nivel en un training board, intentando problemas que tomaran varios entrenamientos completar. Objetivo: Aumentar la fuerza máxima y la producción de potencia en terreno de board pronunciado.' where code = 'SP0011';
update exercises set name = 'Esfuerzos Máximos en Board - Extendido', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Un entrenamiento extendido de board a verdadera intensidad de alto nivel, con más tiempo para trabajar problemas límite y acumular intentos de calidad. Objetivo: Aumentar la fuerza máxima y la producción de potencia con un mayor volumen de esfuerzo de alto nivel.' where code = 'SP0012';
update exercises set name = 'Intervalos de Fuerza', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Repite boulders difíciles pero submaximos en series estructuradas con recuperación completa. Opera cerca de tu umbral de fuerza superior en todas las series. Objetivo: Aumentar la resistencia de fuerza y la producción de fuerza repetible. Descanso: 5 min entre series' where code = 'SP0013';
update exercises set name = 'Juego de Boulder', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Experimenta con el movimiento en un estímulo de baja presión creando o modificando problemas. Prueba estilos, betas y posiciones corporales poco familiares. Objetivo: Expandir el vocabulario de movimiento, la coordinación y la resolución creativa de problemas.' where code = 'SP0014';
update exercises set name = 'Boulder volumen', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Completa 20 boulders en una hora a una intensidad desafiante pero manejable, apuntando a encadenar o completar cada uno en dos intentos. Objetivo: Construir capacidad y tolerancia para boulder sostenido de alto volumen a una intensidad media controlada.' where code = 'SP0015';
update exercises set name = 'Pausas en Board', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'En cada movimiento de un problema de board pronunciado, suelta los pies y manten 3 segundos antes de volver a colocarlos. Manten el control en todo momento. Objetivo: Desarrollar fuerza de contacto, estabilidad de hombro y control posicional bajo carga. Descanso: 5 min entre series' where code = 'SP0016';
update exercises set name = 'Pirámide de Boulder', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Escala problemas progresivamente más difíciles hasta tu máximo, luego trabaja de vuelta hacia grados más fáciles. Si tienes menos series, detente en la cima. Objetivo: Desarrollar la fuerza y el manejo de la fatiga mediante variación de intensidad controlada a través de una pirámide estructurada. Descanso: 2 min 30 s entre series' where code = 'SP0017';
update exercises set name = 'MoonBoard', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Intenta problemas de referencia desafiantes de MoonBoard con 3 intentos por problema y recuperación completa entre series. Objetivo: Mejorar la fuerza de tracción máxima y la resolución rápida de problemas en terreno pronunciado y estandarizado. Descanso: 6 min entre series' where code = 'SP0018';
update exercises set name = 'Sesión de Board', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Escala problemas difíciles en un training board con 3 intentos por problema y recuperación completa entre series. Objetivo: Construir fuerza y potencia de alto nivel mientras mejoras tu capacidad de ejecutar movimientos difíciles en terreno de board pronunciado. Descanso: 6 min entre series' where code = 'SP0019';
update exercises set name = 'Simulación de Competencia - Final', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Simula una competencia estilo final con 4 minutos por problema y recuperación completa entre boulders. Maximiza la calidad por intento. Objetivo: Desarrollar el rendimiento máximo bajo demanda psicológica máxima y presión de tiempo. Descanso: 10 min entre series' where code = 'SP0020';
update exercises set name = 'Simulación de Competencia - Semifinal', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Replica las demandas de una competencia de semifinal con 5 minutos por problema y descanso estructurado. Escala bajo presión. Objetivo: Mejorar la compostura, la precisión y la ejecución a alta intensidad bajo restricciones estilo competencia. Descanso: 5 min entre series' where code = 'SP0021';
update exercises set name = 'Tensión - Manos Fijas', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Manten las manos fijas en dos presas mientras trasladas los pies a través de la pared en terreno pronunciado, generando el movimiento desde el tren inferior y el core. Objetivo: Desarrollar el manejo de la tensión, la fuerza posicional y la transferencia eficiente de fuerza a través de los pies en terreno pronunciado. Descanso: 3 min entre series' where code = 'SP0022';
update exercises set name = 'Volumen de Board', muscle_groups = '["Dedos","Hombro"]'::jsonb, description = 'Acumula un número alto de problemas de board desafiantes a intensidad submáxima, completando cada uno en 1-3 intentos antes de continuar. Objetivo: Construir capacidad de trabajo y resistencia de fuerza en terreno pronunciado mediante un esfuerzo constante y de alto volumen.' where code = 'SP0023';
